module.exports = {
    CLEAR_LOCAL_NOTIFICATION: "CLEAR_LOCAL_NOTIFICATION",
    SET_LOCAL_NOTIFICATIONS: "SET_LOCAL_NOTIFICATIONS",
    LOAD_APP_STATE: "LOAD_APP_STATE",
    GET_DECK: "GET_DECK",
    SUBMIT_NEW_DECK: 'SUBMIT_NEW_DECK',
    ADD_CARD_TO_DECK: "ADD_CARD_TO_DECK",
    QUIZ_VISITED: "QUIZ_VISITED",
    CHECK_QUIZ_VISITED: "CHECK_QUIZ_VISITED",
};